//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DdsFileTypePlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DdsFileTypePlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC6H / BC7 Compression Speed.
        /// </summary>
        internal static string BC7CompressionSpeed_DisplayName {
            get {
                return ResourceManager.GetString("BC7CompressionSpeed_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string BC7CompressionSpeed_Fast {
            get {
                return ResourceManager.GetString("BC7CompressionSpeed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string BC7CompressionSpeed_Medium {
            get {
                return ResourceManager.GetString("BC7CompressionSpeed_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string BC7CompressionSpeed_Slow {
            get {
                return ResourceManager.GetString("BC7CompressionSpeed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube Map from crossed image.
        /// </summary>
        internal static string CubeMap_Description {
            get {
                return ResourceManager.GetString("CubeMap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4G4R4A4 (Linear, A4R4G4B4).
        /// </summary>
        internal static string DdsFileFormat_B4G4R4A4 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B4G4R4A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B5G5R5A1 (Linear, A1R5G5B5).
        /// </summary>
        internal static string DdsFileFormat_B5G5R5A1 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B5G5R5A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B5G6R5 (Linear, R5G6B5).
        /// </summary>
        internal static string DdsFileFormat_B5G6R5 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B5G6R5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B8G8R8 (Linear, R8G8B8).
        /// </summary>
        internal static string DdsFileFormat_B8G8R8 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B8G8R8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B8G8R8A8 (Linear, A8R8G8B8).
        /// </summary>
        internal static string DdsFileFormat_B8G8R8A8 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B8G8R8A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B8G8R8A8 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_B8G8R8A8Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_B8G8R8A8Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B8G8R8X8 (Linear, X8R8G8B8).
        /// </summary>
        internal static string DdsFileFormat_B8G8R8X8 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B8G8R8X8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B8G8R8X8 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_B8G8R8X8Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_B8G8R8X8Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC1 (Linear, DXT1).
        /// </summary>
        internal static string DdsFileFormat_BC1 {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC1 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_BC1Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC1Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC2 (Linear, DXT3).
        /// </summary>
        internal static string DdsFileFormat_BC2 {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC2 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_BC2Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC2Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC3 (Linear, DXT5).
        /// </summary>
        internal static string DdsFileFormat_BC3 {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC3 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_BC3Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC3Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC4 (Linear, Unsigned).
        /// </summary>
        internal static string DdsFileFormat_BC4Unsigned {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC4Unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC5 (Linear, Signed).
        /// </summary>
        internal static string DdsFileFormat_BC5Signed {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC5Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC5 (Linear, Unsigned).
        /// </summary>
        internal static string DdsFileFormat_BC5Unsigned {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC5Unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC6H (Linear, Unsigned, DX 11+).
        /// </summary>
        internal static string DdsFileFormat_BC6HUnsigned {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC6HUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC7 (Linear, DX 11+).
        /// </summary>
        internal static string DdsFileFormat_BC7 {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC7 (sRGB, DX 11+).
        /// </summary>
        internal static string DdsFileFormat_BC7Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC7Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R32 (Linear, Float).
        /// </summary>
        internal static string DdsFileFormat_R32Float {
            get {
                return ResourceManager.GetString("DdsFileFormat_R32Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R8G8B8A8 (Linear, A8B8G8R8).
        /// </summary>
        internal static string DdsFileFormat_R8G8B8A8 {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8G8B8A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R8G8B8A8 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_R8G8B8A8Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8G8B8A8Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R8G8B8X8 (Linear, X8B8G8R8).
        /// </summary>
        internal static string DdsFileFormat_R8G8B8X8 {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8G8B8X8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R8G8 (Linear, Signed, V8U8).
        /// </summary>
        internal static string DdsFileFormat_R8G8Signed {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8G8Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R8G8 (Linear, Unsigned, A8L8).
        /// </summary>
        internal static string DdsFileFormat_R8G8Unsigned {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8G8Unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R8 (Linear, Unsigned, L8).
        /// </summary>
        internal static string DdsFileFormat_R8Unsigned {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8Unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error diffusion dithering.
        /// </summary>
        internal static string ErrorDiffusionDithering_Description {
            get {
                return ResourceManager.GetString("ErrorDiffusionDithering_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Metric.
        /// </summary>
        internal static string ErrorMetric_DisplayName {
            get {
                return ResourceManager.GetString("ErrorMetric_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perceptual.
        /// </summary>
        internal static string ErrorMetric_Perceptual {
            get {
                return ResourceManager.GetString("ErrorMetric_Perceptual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform.
        /// </summary>
        internal static string ErrorMetric_Uniform {
            get {
                return ResourceManager.GetString("ErrorMetric_Uniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectDraw Surface (DDS).
        /// </summary>
        internal static string FileType_Name {
            get {
                return ResourceManager.GetString("FileType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Discussion.
        /// </summary>
        internal static string ForumLink_Description {
            get {
                return ResourceManager.GetString("ForumLink_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        internal static string ForumLink_DisplayName {
            get {
                return ResourceManager.GetString("ForumLink_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Mip Maps.
        /// </summary>
        internal static string GenerateMipMaps_Description {
            get {
                return ResourceManager.GetString("GenerateMipMaps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive (Sharp).
        /// </summary>
        internal static string ResamplingAlgorithm_AdaptiveHighQuality {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_AdaptiveHighQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicubic.
        /// </summary>
        internal static string ResamplingAlgorithm_Cubic {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_Cubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicubic (Smooth).
        /// </summary>
        internal static string ResamplingAlgorithm_CubicSmooth {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_CubicSmooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fant.
        /// </summary>
        internal static string ResamplingAlgorithm_Fant {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_Fant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanczos.
        /// </summary>
        internal static string ResamplingAlgorithm_Lanczos3 {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_Lanczos3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinear.
        /// </summary>
        internal static string ResamplingAlgorithm_Linear {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinear (Low Quality).
        /// </summary>
        internal static string ResamplingAlgorithm_LinearLowQuality {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_LinearLowQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Neighbor.
        /// </summary>
        internal static string ResamplingAlgorithm_NearestNeighbor {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_NearestNeighbor", resourceCulture);
            }
        }
    }
}
